version: '3'
services:
  daily-content:
    container_name: daily-content-backend
    build:
      context: ../../.
      dockerfile: Dockerfile
    env_file:
      - ./values.env
    ports:
      - 8080:8080
    restart: always
  db:
    image: "postgres:12.0"
    container_name: daily-content-database
    ports:
      - "5432:5432"
    volumes:
    - devDB:/var/lib/postgresql/data
volumes:
  devDB: